### ISSUE TITLE
TypeError: __init__() missing 1 required positional argument: 'device'

### ISSUE THREAD

**Issue by bimintelligence** [PeiChangY/-BERT-BILSTM-DGCNN-ATTENTION-CRF-#10]
好像是在说device未定义
![image](https://github.com/PeiChangY/-BERT-BILSTM-DGCNN-ATTENTION-CRF-/assets/73410751/6324a351-0c7b-41ea-b139-b08ccd4e00a5)
![image](https://github.com/PeiChangY/-BERT-BILSTM-DGCNN-ATTENTION-CRF-/assets/73410751/160f07d6-2bbb-4066-9c20-2e65e6972542)

**Comment by PeiChangY** [comment]
上面不是定义了&nbsp; 我这显示没问题&nbsp; &nbsp;你看看是否是pytorch没装gpu版




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PeiChangY/-BERT-BILSTM-DGCNN-ATTENTION-CRF-"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年7月4日(星期二) 上午10:55
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[PeiChangY/-BERT-BILSTM-DGCNN-ATTENTION-CRF-] TypeError: __init__() missing 1 required positional argument: 'device' (Issue #10)





 
好像是在说device未定义
